# Generated by Django 3.2.13 on 2022-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('student_number', models.TextField()),
                ('study_programm', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
            ],
        ),
    ]
