# Generated by Django 3.2.13 on 2022-05-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='study_programm',
        ),
    ]
