# Generated by Django 3.2.13 on 2022-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220504_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(default='male'),
            preserve_default=False,
        ),
    ]
