# Generated by Django 3.2.13 on 2022-05-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='study_program',
            field=models.TextField(default='Computing Science'),
            preserve_default=False,
        ),
    ]
