# Generated by Django 3.2.13 on 2022-05-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='student_number',
            new_name='studentNumber',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='study_program',
            new_name='studyProgram',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], default='m', max_length=1),
        ),
    ]
