# Generated by Django 4.0.4 on 2022-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='groupCourse',
        ),
        migrations.AddField(
            model_name='groups',
            name='course',
            field=models.CharField(choices=[('', ''), ('CaPt', 'calculus and probability theory'), ('HiC', 'hacking in C')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='groups',
            name='groupName',
            field=models.CharField(max_length=100),
        ),
    ]
