# Generated by Django 4.0.4 on 2022-05-24 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=100)),
                ('groupSize', models.IntegerField(default=4)),
                ('groupDescription', models.CharField(default='', max_length=500)),
                ('course', models.CharField(choices=[('', 'None'), ('CaPT', 'Calculus'), ('HiC', 'Hacking in C')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('studentNumber', models.TextField()),
                ('studyProgram', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], default='m', max_length=1)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastructures.group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastructures.profile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='datastructures.Membership', to='datastructures.profile'),
        ),
    ]
