# Generated by Django 4.0.4 on 2022-05-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='choices',
            field=models.ManyToManyField(to='datastructures.coursechoice'),
        ),
    ]
