# Generated by Django 4.0.4 on 2022-05-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0005_remove_profile_choices_delete_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('', 'None'), ('CaPT', 'Calculus'), ('HiC', 'Hacking in C')], default='', max_length=100),
        ),
    ]
