# Generated by Django 4.0.4 on 2022-05-31 09:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0006_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'None'), ('CaPT', 'Calculus'), ('HiC', 'Hacking in C')], default='', max_length=9),
        ),
    ]
