# Generated by Django 4.0.4 on 2022-05-31 10:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0007_alter_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CaPT', 'Calculus'), ('HiC', 'Hacking in C')], default='', max_length=8),
        ),
    ]
