# Generated by Django 4.0.4 on 2022-05-31 10:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0008_alter_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(choices=[('Calculus and Probability Theory', 'Calculus and Probability Theory'), ('Hacking in C', 'Hacking in C')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Calculus and Probability Theory', 'Calculus and Probability Theory'), ('Hacking in C', 'Hacking in C')], default='', max_length=44),
        ),
    ]
