# Generated by Django 4.0.4 on 2022-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0011_remove_profile_firstname_remove_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.TextField(default=''),
        ),
    ]
