# Generated by Django 4.0.4 on 2022-06-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='group_joined',
            field=models.BooleanField(default=False),
        ),
    ]
