# Generated by Django 4.0.4 on 2022-06-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0014_membership_group_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='date_joined',
        ),
    ]
