# Generated by Django 4.0.4 on 2022-06-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0011_auto_20220607_1347'),
        ('datastructures', '0016_alter_profile_studyprogram'),
    ]

    operations = [
    ]
