# Generated by Django 3.2.13 on 2022-06-09 14:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0019_auto_20220609_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(choices=[('0', 'Calculus and Probability Theory'), ('1', 'Hacking in C')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Calculus and Probability Theory'), ('1', 'Hacking in C')], default='', max_length=3),
        ),
    ]
