# Generated by Django 3.2.13 on 2022-06-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0020_auto_20220609_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('fale', 'fale'), ('other', 'other')], default='male', max_length=10),
        ),
    ]
