# Generated by Django 3.2.13 on 2022-06-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastructures', '0023_auto_20220610_2029'),
        ('datastructures', '0023_auto_20220610_2102'),
    ]

    operations = [
    ]
